### ISSUE TITLE
Please consider re-licensing under a true open source license

### ISSUE THREAD

**Issue by jaredsmith** [TIBCOSoftware/flogo#15]
I love the fact that you consider Flogo as open source, but for people like me who spend much of their time dealing with open source licenses, the license on this package is problematic.  (By way of background, I stumbled across this project today and my first thought was "Great, let me package this up for Fedora/RHEL/CentOS", but due the license, I can't.)

In short, the field of use restrictions in the license ("internal business use only") means that this isn't truly open source by the generally accepted guidelines (FSF, OSI, Debian Free Software Guidelines, Fedora Packaging Guidelines, etc.).

Would you please reconsider licensing this software under a more commonly accepted open source license, such as the MIT, Apache 2.0, or GPL licenses?

**Comment by tibmatt** [comment]
Hi, I think you are referring only to the flogo repo which contains the samples (i.e. This one). The actual components of flogo - Flogo-lib, flogo-cli etc have a BSD style license.

**Comment by rkozhikk** [comment]
@jaredsmith Please refer to [flogo-cli license](https://github.com/TIBCOSoftware/flogo-cli/blob/master/TIBCO%20LICENSE.txt),  [flogo-lib license](https://github.com/TIBCOSoftware/flogo-lib/blob/master/TIBCO%20LICENSE.txt) or [flogo-services license](https://github.com/TIBCOSoftware/flogo-services/blob/master/TIBCO%20LICENSE.txt). They are all BSD-style. The top-level flogo repo is under a samples license because it doesnt have any real software, just samples and a few docs. 

If you have any further questions or concerns, let us know and we'd love to work with you to address them.

**Comment by jaredsmith** [comment]
Thanks for the clarification!  That helps.
