### ISSUE TITLE
integration into tibco products

### ISSUE THREAD

**Issue by joeblew99** [TIBCOSoftware/flogo#21]
Looks interesting....

Can i ask some high ball questions ?

1. Your planning to write extensiosn that feed into the current tibco enterprise products ? Maybe some message queues or data analytics ?

2. Are you planning on open sourcing anything related to the management of IOT devices. Updates, security, etc.

thansk you ..

**Comment by rkozhikk** [comment]
Hey @joeblew99, great questions! 

1. Yes, Flogo already integrates with TIBCO's Enterprise products through [TIBCO eFTL](http://www.tibco.com/products/automation/enterprise-messaging/eftl) using the WebSocket activity, beyond standard Web APIs and Web Services. eFTL being a WebSockets-compatible messaging middleware would be typically be the entrypoint into other products like FTL, BusinessWorks, StreamBase and Spotfire running in the cloud / on-premise. We can probably publish a reference architecture if that helps. 

2. IoT device management itself is not an area of focus for Project Flogo. We are super-focused on building the lightest integration engine with an edge-native design so that you can run on the device itself. We would love Flogo to complement existing IoT platforms. Typically, Device ID, OTA, security, etc. are either provided by IoT platforms like AWS, Predix, Azure, etc. (there are about 125 of them at last count & Flogo is not building yet another platform :). We have also seen folks interested in DIY using frameworks like PlatformIO, Resin.io, etc. and we think Flogo is a natural complement to them. 
 
HTH, happy to go into more details if that helps.

**Comment by joeblew99** [comment]
thanks @rkozhikk 

About 1. Yes any more info on this is really useful for me. Looking to see the big picture 

On 2. I used Resin.io, but also ubuntu core, and i also build my own :) must be the 126 th. 

I guess i have to wonder a bit who in terms of roles would use Flogo.  It reminds me of the old days using tibco rendevous a bit and configureing this giant XML based orchestration mapping in a "hub and spoke" messaging architecture. Thats just my own biased slant on it.

I can see it being great for ETL, and lets face it if the business analyst can do it, and not me to map the external data to our internal data model, thats one more thing i dont have to do:)

I am also thinking about orchestration for microservices. When you have data for "Patients" in one microservce and data for "Experiments done on patients by mad scientists" in another microservice and you want to do the equivalant of a "find me all patients that had experiment X done on them Or anything more complex you need to use a map reduce style of programming at the layer just above each microservice. People use Spark and other stuff. But i can see that flogo provides primitives (basically the flogo standard library) to allow others to write "flows" and those can be "map reduce".


---

My last thing is where is the state ? I have not played with flogo, but only read the code a bit.
I am just curious where the state resides. Seem to be borrowing idea from a reFlux like architecture (and immutable data types), i am presuming that its where the orchestration layer is. Hecne why you can restart half way into a flow, etc

Sorry about being so imprecise here.. i knwo this is not a github issue at all
