### ISSUE TITLE
Support for $INPUT["xxx"] in flogo

### ISSUE THREAD

**Issue by KanchanPaul** [TIBCOSoftware/flogo#244]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request
[] general question
```

**Current behavior (how does the issue manifest):**
Currently, flogo mapping only supports  “mapTo”: “xxx”, requesting to support “mapTo”:$INPUT["xxx"]. Fails to display mapping values in UI.

**Expected behavior:**
Interpret “mapTo”:$INPUT["xxx"]  and disaply mapping values in UI accordingly. 

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
Hi @KanchanPaul, just for clarity, what is the reason you'd like to see mappings like this? I see little reason for this when you're mapping to an input param on an activity... you're scoped within that activity and you're obviously mapping to activity inputs...

**Comment by mellistibco** [comment]
also, $activity, etc indicates a mapping resolver. In this case there is no reason to resolve input...

**Comment by vijaynalawade** [comment]
@mellistibco This is related to **mapTo** in mapping and related to special characters when mapping to child node in the object.  @lixingwang can you elaborate more on the usage.

**Comment by mellistibco** [comment]
@vijaynalawade i get that, but still don't get the idea of having a resolver for mapTo?

```json
  "mappings": {
    "input": [
      {
        "mapTo": "$input['message']", <--- why $input rather than just message? the mapping section is called input :)
        "type": "expression",
        "value": "hello"
      }
    ]
  }
```

**Comment by mellistibco** [comment]
but mapTo maps to the input param, it can already handle any special characters... mapTo: "my field name" would work...

**Comment by mellistibco** [comment]
also, its in quotes, as far as the json doc is concerned its valid... you can stick any special characters you want in there, no? whatever the engine will accept

**Comment by fcastill** [comment]
The mapper is not taking "mapTo" as a property name but as an expression. I think the simplest case is when you have an activity that defines an input like this:

```
"input": [{
  "name": "foo.bar",
  "type": "object"
}]
``` 

Then if you specify this mapping:

```json
{
  "mapTo": "foo.bar",
  "type": "expression",
  "value": "555"
}
```

The mapper will understand this:

```json
{
  "foo": {
     "bar": 555
   }
}
```

When you actually want this:

```json
{
  "foo.bar": 555
}
```

So you need somehow to indicate that you want to access "foo.bar", which was resolved so far as:
```
{
  "mapTo": "$INPUT['foo.bar']",
  "type": "expression",
  "value": "555"
}
```

I think the `$INPUT` prefix (which is not a resolver here) is there to have the same expression syntax than the expression language used in the `value` property. When you assume that the "expression" in `mapTo` should be parsed the same as an expression in `value` then there's a bunch of other "special" characters to be considered besides the dot (`.`) character. For example a rest header like `Accept-Content` cannot be mapped as `{ "mapTo": "headers.Accept-Content"}` because that parses as `headers.Accept` `MINUS` `Content` (an operation, not a property access).

With that all these `mapTo` permutations needs to be supported as they mean same:
- `a.b.c`
- `a.b['c']`
- `a.['b'].c`
- `a.b['c']`
- `$INPUT['a']['b']['c']`
- `$INPUT['a'].b['c']`
- `$INPUT.a.b.c` 
- `$INPUT.a.b['c']`

I wonder now about the consistency with the other mapping types, for example is this supported?

```
{
  "mapTo": "$INPUT['a']",
  "type": "assign", <----
  "mapTo": "$activity[xyz]['b']"
}

```

**Comment by lixingwang** [comment]
@fcastill is absolutely right.  Fabian and I made the decision before.   UI want to make sure it is a valid expression(UI way) so it added $INPUT prefix for mapTo field.

At runtime side, we also allow $INPUT for mapto but which is useless, so we will remove $INPUT before do mapper.  

@fcastill can we revisit to see if we can remove $INPUT from UI? now it makes confuse for FLOGO.

**Comment by fm-tibco** [comment]
`{
  "mapTo": "$INPUT['a']",
  "type": "assign", <----
  "mapTo": "$activity[xyz]['b']"
}`

Is not supported.  There should not be any resolvers on the mapTo side.  The mapTo side is not an expression, it is is a variable you are mapping to.   I believe the only issue is if the variable you are mapping to has spaces or a variable name that is typically invalid in most languages.  First of all are we allowing that?   Can activity or flow  inputs/outputs have either of those?  We should probably restrict variable names like most languages.. ie. must start with letter or underscore and can only contain letters, numbers or underscores after that.   That should work without anything special I believe.

The only place I can see were spaces and periods can be used in an indentifier is probably just the key in a map.  We'll have to introduce MAP data type to formally support this.

**Comment by mellistibco** [comment]
Closing this issue. Will not add a resolver to the mapTo param as it does not fit the definition of a resolver.
