### ISSUE TITLE
Validation Error using Flogo Web

### ISSUE THREAD

**Issue by lhollyer** [TIBCOSoftware/flogo#418]
I keep getting a validation error when trying to build my Flogo project:

`2018-10-23T14:14:20.778Z - info:  FlogoError: Validation error
    at Validator.validate (/tmp/flogo-web/build/server/common/validator/validator.js:24:34)
    at Exporter.export (/tmp/flogo-web/build/server/modules/exporter/exporter.js:61:20)
    at executeExport (/tmp/flogo-web/build/server/modules/exporter/index.js:71:25)
    at exportStandard (/tmp/flogo-web/build/server/modules/exporter/index.js:65:10)
    at _activities.ActivitiesManager.find.then.activitySchemas (/tmp/flogo-web/build/server/modules/apps/index.v2.js:271:104)
    at <anonymous>
local/engines/flogo-web/src/flogo-web/vendor?:  true`

I'm running Docker 17.12.0-ce on MacOS using Chrome as my browser. I've imported my project that worked in previous versions of Flogo (~Dec 2017) but won't build when trying to build to Linux/ARM.

Attached is the project in question. Thanks!

[finalapp8withoutinvokes.json.zip](https://github.com/TIBCOSoftware/flogo/files/2506691/finalapp8withoutinvokes.json.zip)

**Comment by retgits** [comment]
Hi @lhollyer, looking at the JSON (and after trying the app myself as well 😅) it looks like the app is built using the "legacy app model" which we deprecated a while ago. The error you're seeing is because the Web UI doesn't know how to migrate between the old and new model. I believe that code was removed in one of the previous version of the Web UI (@fcastill could confirm that).

**Comment by lhollyer** [comment]
Hi @retgits - thanks for the quick reply! Is there any way I can migrate the code, or is it best I remake it? Every time I try to export as an app or flows it just tells me "Unknown error" with no details in the log 👎

**Comment by retgits** [comment]
Sorry 😞 

I'm not sure if there is a way to move between the old and new version of the app model (but I think @fcastill could confirm that). Looking through the app, you might want to consider updating a few things (like using the string.concat function as opposed to the combine activity) as the Web UI has gotten quite a significant overhaul over the past months (I also really recommend using the latest version if you haven't pulled that yet).

**Comment by mellistibco** [comment]
Hi @lhollyer you should be able to use a previous version of Flogo. I think v 0.5.5, import your app and then export it again. That SHOULD (@fcastill?) convert the app for you and then you can continue using 0.5.6.

**Comment by fcastill** [comment]
It's an internal bug caused by the task and links ids being numbers instead of strings. 

A woekaround is converting all the ids to strings like this: https://gist.github.com/fcastill/09b8927897f4e25452f12564bcf06b47#file-legacy-json

And this is the same app but using the new model: https://gist.github.com/fcastill/09b8927897f4e25452f12564bcf06b47#file-new-model-json

**Comment by fcastill** [comment]
> Hi @lhollyer you should be able to use a previous version of Flogo. I think v 0.5.5, import your app and then export it again. That SHOULD (@fcastill?) convert the app for you and then you can continue using 0.5.6.

v0.5.6 also supports that except for this problem w/ number ids

**Comment by lhollyer** [comment]
> It's an internal bug caused by the task and links ids being numbers instead of strings.
> 
> A workaround is to convert all the ids to strings like this: https://gist.github.com/fcastill/09b8927897f4e25452f12564bcf06b47#file-legacy-json
> 
> And this is the same app but using the new model: https://gist.github.com/fcastill/09b8927897f4e25452f12564bcf06b47#file-new-model-json

Thanks so much for this, you've solved my problem!
