### ISSUE TITLE
Flogo docker environment is not getting up and running

### ISSUE THREAD

**Issue by ochanig33** [TIBCOSoftware/flogo#499]
STR:
1. In docker toolbox, try running this command: **docker run -it -p 3303:3303 flogo/flogo-docker eula-accept**
2. One of the docker image is getting stuck and not getting downloaded.

Note: This issue is with latest image tag but when I changed the tag to v0.9.0, I am getting below error
docker run -it -p 3303:3303 flogo/flogo-docker:v0.9.0 eula-accept
Unable to find image 'flogo/flogo-docker:v0.9.0' locally
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/flogo/flogo-docker/manifests/v0.9.0: dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: read udp 10.0.2.15:57384->10.0.2.3:53: i/o timeout.
_Seems some issue with change in registry._

Attaching the image for your reference.

![1](https://user-images.githubusercontent.com/23337654/64072489-e3373c80-ccac-11e9-9f4c-a211f910cfaa.PNG)

![2](https://user-images.githubusercontent.com/23337654/64073246-a3765200-ccb8-11e9-9760-f8d171a001d1.PNG)

**Comment by fcastill** [comment]
This looks like an issue with your network or setup. Maybe a firewall/vpn issue? I've cleared my docker cache and tried downloading multiple flogo images and they all worked.

Have you tried downloading other docker images (that are not already cached) and see if they work? You can also try clearing up your docker cache. Also, since you're using the  Docker Toolbox for windows this could be a VM configuration issue. Maybe you can give a try to native Docker for Windows? (toolbox is deprecated)

**Comment by mellistibco** [comment]
Closing, if this is still an issue please reopen.
