### ISSUE TITLE
CF Buildpack for Flogo

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo#65]
A cloud foundry buildpack for Flogo to enable deployments across CF PaaS environments.

**Comment by retgits** [comment]
You don't really need to have a Cloud Foundry specific build pack for Flogo. With the Cloud Foundry Binary Buildpack you can run arbitrary binary web servers on CF without the need to have a specific build pack for that language. Since Flogo can compile down to a binary that seems a nicer option.

**Prerequisites:**
* You'll need a binary that is able to run on the same OS as CF is deployed (most likely Linux)
* You'll need to make sure you're using port 8080 for your *Receive HTTP Message* trigger (this seems to be the default port for the binary build pack, though as a nice to have I'd suggest making it possible to use the PORT environment variable in the trigger as described [here](https://github.com/TIBCOSoftware/flogo-lib/issues/123)).

**Steps to deploy:**
1) Either build a Linux based app using the Web UI or build one using the cli (remember to set `GOOS=Linux` when building)
2) Make sure the app is executable: `chmod +x <appname>`
3) Push to PCF: `cf push <name in pcf> -c './<appname>' -b binary_buildpack`

More details on the binary build pack can be found [here](https://docs.cloudfoundry.org/buildpacks/binary/index.html)

**Comment by mellistibco** [comment]
Reopening and making it a documentation issue then :) thanks @retgits

**Comment by mellistibco** [comment]
Push instructions outlined by @retgits to docs site

**Comment by rkozhikk** [comment]
@retgits - can this go to flogo.io docs or wiki too?
