### ISSUE TITLE
Documentation: flogogen not rendering properly

### ISSUE THREAD

**Issue by Adirio** [TIBCOSoftware/flogo#74]
![image](https://user-images.githubusercontent.com/522770/31601734-26c40b9a-b25b-11e7-9fb6-08bf91f53bc7.png)

When reading it on Github the ending ``` is correctly identified but when using flogo.io documentation page it isn't, and is then swapping everything after it.

**Comment by Adirio** [comment]
Am I the only one that doesn't see this fixed? I'm even using a different explorer to avoid cacheing issues. I though it could be just it being solved in GitHub but not ported yet to the docs (I'm not sure if Hugo requires this kind of process or if he reads it from GitHub directly) but I'm seeing the new section FaaS now and that was merged after the solution to this issue but I'm still seeing the same problem.

**Comment by retgits** [comment]
It might be :( 

The snippet of HTML that caused the problem is now rendered correctly in the gh-pages branch (the closing code tag was missing due to extra spaces at the end):
```
<p>With the trigger command of <strong>flogogen</strong> you can create a custom flogo trigger. To do so, run:</p>

<pre><code>flogogen trigger mytrigger
</code></pre>
```
I've looked at the page on different browsers and different machines and it displays the page correctly. Can you try doing an `empty cache and hard reload` if you're using Chrome and see if that forces your machine to get the latest pages?

**Comment by Adirio** [comment]
Opened developer tools and selected that option from the dropdown menu that appears when you right-click the reload button a couple times and still nothing.

We are looking at the same [place](https://tibcosoftware.github.io/flogo/flogo-cli/flogogen-cli/#action), aren't we?
